services:
  m3u-checker:
    image: ghcr.io/je668/m3u-checker:latest
    container_name: m3u-checker
    restart: always
    ports:
      - "5123:5123"
    environment:
      - TZ=Asia/Shanghai
      # 开启硬件加速开关
      - USE_HWACCEL=true 
    devices:
      # 映射 Intel 集显设备
      - /dev/dri:/dev/dri 
    volumes:
      - ./iptv_data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
